// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuhMgN7b4FhY8pF63n3AcPR5PMEjJpsds',
    appId: '1:1070408477943:web:54f2a443bf783c964c37f2',
    messagingSenderId: '1070408477943',
    projectId: 'schoolmis-52d17',
    authDomain: 'schoolmis-52d17.firebaseapp.com',
    databaseURL: 'https://schoolmis-52d17-default-rtdb.firebaseio.com',
    storageBucket: 'schoolmis-52d17.appspot.com',
    measurementId: 'G-PRXQ49274R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUspWGJg4CkzOZFYdHRlYpDa5AdztQU9o',
    appId: '1:1070408477943:android:dd59fdb474f3e7604c37f2',
    messagingSenderId: '1070408477943',
    projectId: 'schoolmis-52d17',
    databaseURL: 'https://schoolmis-52d17-default-rtdb.firebaseio.com',
    storageBucket: 'schoolmis-52d17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzld3c5RSCBVnvBcQldPv17g_u9OUqxHA',
    appId: '1:1070408477943:ios:ea5bdb1ce4034c464c37f2',
    messagingSenderId: '1070408477943',
    projectId: 'schoolmis-52d17',
    databaseURL: 'https://schoolmis-52d17-default-rtdb.firebaseio.com',
    storageBucket: 'schoolmis-52d17.appspot.com',
    iosBundleId: 'com.example.firebaseAuthSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzld3c5RSCBVnvBcQldPv17g_u9OUqxHA',
    appId: '1:1070408477943:ios:dc77a07498affb634c37f2',
    messagingSenderId: '1070408477943',
    projectId: 'schoolmis-52d17',
    databaseURL: 'https://schoolmis-52d17-default-rtdb.firebaseio.com',
    storageBucket: 'schoolmis-52d17.appspot.com',
    iosBundleId: 'com.example.firebaseAuthSample.RunnerTests',
  );
}
